version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - interaction-network

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "user-interactions:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - interaction-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - interaction-network

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/
      - DASHBOARD_HOST=0.0.0.0
    ports:
      - "8050:8050"  
    depends_on:
      - kafka
      - mongodb
    networks:
      - interaction-network
    command: python main.py

networks:
  interaction-network:
    driver: bridge

volumes:
  mongodb_data: 